version: '3.0'
services:
  price_checker_by:
    container_name: price-checker-by
    image: price-checker-by
    build:
      context: .
      args:
        TIME_ZONE: ${TIME_ZONE}
        CHROMEDRIVER_DOWNLOAD_LINK: ${CHROMEDRIVER_DOWNLOAD_LINK}
        CHROME_DOWNLOAD_LINK: ${CHROME_DOWNLOAD_LINK}
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      DRIVER_URL: ${DRIVER_URL}
      CRON_TIME: ${CRON_TIME}
    depends_on:
      - db
    ports:
      - 8080:8080
      - 5005:8000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5433:5432